import LocalizedStrings from 'react-localization';

let strings = new LocalizedStrings({
    id: {
        add: 'Tambah',
        cancel: 'Batal',
        edit: 'Ubah',
        update: 'Ubah',
        save: 'Simpan',
        delete_confirm: 'Konfirmasi Hapus',
        delete_data: 'Hapus Data',
        deleting: 'Menghapus...',
        delete: 'Hapus',
        has_been_deleted: 'Data Telah Berhasil Dihapus',
        has_been_edited: 'Telah Berhasil Diubah',
        has_been_added: 'Telah Ditambahkan',
        preview: 'Lihat',
        settings: 'Settings',
        success_add: 'Berhasil Tambah',
        name: 'Nama',
        filter: 'Filter',
        logout: 'Keluar',
        question: 'Pertanyaan',
        status: 'Status',
        start: 'Mulai',
        end: 'Berakhir',
        not_have_account: 'Tidak punya akun Tokopedia?',
        login: 'Masuk',
        signup: 'Daftar',
        forgot_password: 'Lupa Password?',
        product_description: 'Descripsi Produk',
        product_info: 'Info Produk',
        next: 'Selanjutnya',
        login_option: 'atau masuk dengan',
        phone_or_email: 'Nomor Ponsel atau Email'
    },
    en: {
        add: 'Add',
        cancel: 'Cancel',
        edit: 'Edit',
        update: 'Update',
        save: 'Save',
        delete_confirm: 'Delete Confirm',
        delete_data: 'Delete Data',
        deleting: 'Deleting...',
        delete: 'Delete',
        has_been_added: 'Has Been Added',
        has_been_edited: 'Has Been Edited',
        has_been_deleted: 'Has Been Deleted',
        preview: 'Preview',
        settings: 'Settings',
        success_add: 'Berhasil Tambah',
        name: 'Name',
        filter: 'Filter',
        logout: 'Logout',
        question: 'Question',
        status: 'Status',
        start: 'Start',
        end: 'End',
        not_have_account: "Don\'t have account Tokopedia?",
        login: 'Login',
        signup: 'Sign Up',
        forgot_password: 'Forgot Password?',
        product_description: 'Product Description',
        product_info: 'Product Info',
        next: 'Next',
        login_option: 'or sign in with',
        phone_or_email: 'Phone Number or Email'
    }
});

export default strings;